export type ReadingFormat = 'COMIC' | 'EPUB' | 'PDF';
export type ReadingStatus = 'WANT' | 'READING' | 'FINISHED';
export type PublicationStatus = 'UNKNOWN' | 'ONGOING' | 'COMPLETED' | 'HIATUS' | 'CANCELLED';
export type TrackingStatus = 'NOT_TRACKING' | 'TRACKING' | 'PAUSED' | 'IGNORED';

export type WorkView = {
  id: string;
  workId: string;
  editionId: string | null;
  monitorFolderId: string | null;
  title: string;
  author: string;
  publisher: string | null;
  type: 'ebook' | 'comic';
  formatValue: ReadingFormat;
  format: string;
  size: string;
  progress: number;
  statusValue: ReadingStatus;
  status: string;
  publicationStatusValue: PublicationStatus;
  publicationStatus: string;
  trackingStatusValue: TrackingStatus;
  trackingStatus: string;
  localLatestVolume: number | null;
  localLatestChapter: number | null;
  localLatestTitle: string | null;
  localLatestAt: string | null;
  ignored: boolean;
  organized: boolean;
  organizeStatus: string;
  metadataQuality: number;
  tags: string[];
  seriesName: string | null;
  seriesIndex: number | null;
  publishedYear: number | null;
  added: string;
  lastRead: string;
  lastReadAt: string | null;
  chapter: string;
  chapterCount: number | null;
  pageCount: number | null;
  desc: string;
  path: string;
  fileHash: string;
  gradient: string;
  coverStatus: string;
  coverUrl: string;
  totalUnits: number;
  readingProgress: number;
  importStatus: string;
  importError: string | null;
  importedAt: string;
  files: Array<{
    id: string;
    path: string;
    mimeType: string;
    kind: string;
    sortOrder: number;
    size: string;
  }>;
  versionCount: number;
  volumeCount: number;
  primaryEditionId: string | null;
  primaryEditionName: string | null;
  recentEditionId: string | null;
  recentVolumeId: string | null;
  volumes: Array<{
    id: string;
    editionId: string;
    title: string;
    volumeIndex: number | null;
    sortOrder: number;
    pageCount: number | null;
    chapterCount: number | null;
    coverUrl: string;
  }>;
  editions: Array<{
    id: string;
    workId: string;
    formatValue: ReadingFormat;
    format: string;
    versionName: string;
    primary: boolean;
    hidden: boolean;
    size: string;
    pageCount: number | null;
    chapterCount: number | null;
    progress: number;
    lastReadAt: string | null;
    coverUrl: string;
    files: WorkView['files'];
    volumes: WorkView['volumes'];
  }>;
};

export type SeriesSummary = {
  name: string;
  bookCount: number;
  latestUpdatedAt: string | null;
};
